# Generated by Django 5.0.2 on 2024-04-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_age_userprofile_challengepreference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dairyallergen',
            new_name='dairyAllergy',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='fishallergen',
            new_name='fishAllergy',
        ),
    ]
