# Generated by Django 5.0.2 on 2024-04-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_rename_dairyallergen_userprofile_dairyallergy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dairyAllergy',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fishAllergy',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.CharField(default='', max_length=255),
        ),
    ]
