# Generated by Django 5.0.2 on 2024-04-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_remove_userprofile_dairyallergy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='shoppingpreferences',
        ),
    ]
