# Generated by Django 5.0.2 on 2024-04-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_remove_userprofile_shoppingpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='financiallimitation',
            field=models.IntegerField(default=0),
        ),
    ]
