# Generated by Django 5.0.2 on 2024-04-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_userprofile_financiallimitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='timecommitment',
            field=models.CharField(default='1-3 hours'),
        ),
    ]
