# Generated by Django 5.0.2 on 2024-04-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_userprofile_timecommitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='time',
            field=models.IntegerField(default=90),
        ),
    ]
