# Generated by Django 5.0.2 on 2024-04-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_userprofile_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='No name set.', max_length=255),
        ),
    ]
