# Generated by Django 5.0.2 on 2024-03-02 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_persontest_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonTest',
        ),
    ]
