# Generated by Django 5.0.2 on 2024-03-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_delete_persontest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.IntegerField()),
                ('sustainability_factor', models.IntegerField()),
                ('image_link', models.CharField(max_length=100)),
            ],
        ),
    ]
