# Generated by Django 5.0.2 on 2024-04-10 00:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_task_due_date_alter_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time_accepted',
            new_name='accepted_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='time_completed',
            new_name='completed_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=api.models.get_week_from_now),
        ),
    ]
