# Generated by Django 5.0.2 on 2024-04-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_time_accepted_task_accepted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
